apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-fundamentals-app-config
  namespace: kubernetes-fundamentals
data:
  # Key-value pairs
  LOG_LEVEL: "Information"
  FEATURE_FLAG_NEWUI: "true"
  
  # Or entire files
  appsettings.json: |
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information"
        }
      },
      "AllowedHosts": "*"
    }